ROLE_CITIZEN = "citizen"
ROLE_GOVERNMENT_EMPLOYEE = "government_employee"
ROLE_WARD_MEMBER = "ward_member"
ROLE_ADMIN = "admin"
ROLE_SUPER_ADMIN = "super_admin"

USER_ROLES = (
    ROLE_CITIZEN,
    ROLE_GOVERNMENT_EMPLOYEE,
    ROLE_WARD_MEMBER,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN,
)

VERIFICATION_PENDING = "pending"
VERIFICATION_APPROVED = "approved"
VERIFICATION_REJECTED = "rejected"
VERIFICATION_SUSPENDED = "suspended"

VERIFICATION_STATUSES = (
    VERIFICATION_PENDING,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    VERIFICATION_SUSPENDED,
)

GOVERNMENT_ID_TYPES = (
    "aadhaar",
    "voter_id",
    "pan",
    "driving_license",
    "passport",
    "ration_card",
    "other",
)

COMPLAINT_STATUS_OPEN = "open"
COMPLAINT_STATUS_UNDER_REVIEW = "under_review"
COMPLAINT_STATUS_ASSIGNED = "assigned"
COMPLAINT_STATUS_IN_PROGRESS = "in_progress"
COMPLAINT_STATUS_RESOLVED = "resolved"
COMPLAINT_STATUS_REJECTED = "rejected"
COMPLAINT_STATUS_REOPENED = "reopened"

COMPLAINT_STATUSES = (
    COMPLAINT_STATUS_OPEN,
    COMPLAINT_STATUS_UNDER_REVIEW,
    COMPLAINT_STATUS_ASSIGNED,
    COMPLAINT_STATUS_IN_PROGRESS,
    COMPLAINT_STATUS_RESOLVED,
    COMPLAINT_STATUS_REJECTED,
    COMPLAINT_STATUS_REOPENED,
)

PRIORITY_LOW = "low"
PRIORITY_MEDIUM = "medium"
PRIORITY_HIGH = "high"
PRIORITY_CRITICAL = "critical"

COMPLAINT_PRIORITIES = (
    PRIORITY_LOW,
    PRIORITY_MEDIUM,
    PRIORITY_HIGH,
    PRIORITY_CRITICAL,
)

PROGRESS_VISIBILITY_PUBLIC = "public"
PROGRESS_VISIBILITY_INTERNAL = "internal"

PROGRESS_VISIBILITIES = (
    PROGRESS_VISIBILITY_PUBLIC,
    PROGRESS_VISIBILITY_INTERNAL,
)

SCHEME_STATUS_DRAFT = "draft"
SCHEME_STATUS_PUBLISHED = "published"
SCHEME_STATUS_ARCHIVED = "archived"

SCHEME_STATUSES = (
    SCHEME_STATUS_DRAFT,
    SCHEME_STATUS_PUBLISHED,
    SCHEME_STATUS_ARCHIVED,
)

IMAGE_UPLOAD_FOLDERS = (
    "complaints",
    "progress",
    "projects",
    "feedback",
    "schemes",
    "identity-documents",
    "general",
)

PROJECT_STATUS_PLANNED = "planned"
PROJECT_STATUS_ACTIVE = "active"
PROJECT_STATUS_ON_HOLD = "on_hold"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_CANCELLED = "cancelled"

PROJECT_STATUSES = (
    PROJECT_STATUS_PLANNED,
    PROJECT_STATUS_ACTIVE,
    PROJECT_STATUS_ON_HOLD,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_CANCELLED,
)

WORKFLOW_STAGE_PLANNING = "planning"
WORKFLOW_STAGE_APPROVAL = "approval"
WORKFLOW_STAGE_EXECUTION = "execution"
WORKFLOW_STAGE_MONITORING = "monitoring"
WORKFLOW_STAGE_CLOSURE = "closure"

PROJECT_WORKFLOW_STAGES = (
    WORKFLOW_STAGE_PLANNING,
    WORKFLOW_STAGE_APPROVAL,
    WORKFLOW_STAGE_EXECUTION,
    WORKFLOW_STAGE_MONITORING,
    WORKFLOW_STAGE_CLOSURE,
)

ACTIVITY_STATUS_NOT_STARTED = "not_started"
ACTIVITY_STATUS_IN_PROGRESS = "in_progress"
ACTIVITY_STATUS_BLOCKED = "blocked"
ACTIVITY_STATUS_COMPLETED = "completed"

PROJECT_ACTIVITY_STATUSES = (
    ACTIVITY_STATUS_NOT_STARTED,
    ACTIVITY_STATUS_IN_PROGRESS,
    ACTIVITY_STATUS_BLOCKED,
    ACTIVITY_STATUS_COMPLETED,
)

MILESTONE_STATUS_PENDING = "pending"
MILESTONE_STATUS_ACHIEVED = "achieved"
MILESTONE_STATUS_DELAYED = "delayed"

PROJECT_MILESTONE_STATUSES = (
    MILESTONE_STATUS_PENDING,
    MILESTONE_STATUS_ACHIEVED,
    MILESTONE_STATUS_DELAYED,
)

FEEDBACK_TYPE_SUGGESTION = "suggestion"
FEEDBACK_TYPE_FEEDBACK = "feedback"
FEEDBACK_TYPE_COMPLAINT = "complaint"
FEEDBACK_TYPE_APPRECIATION = "appreciation"
FEEDBACK_TYPE_REQUEST = "request"

FEEDBACK_TYPES = (
    FEEDBACK_TYPE_SUGGESTION,
    FEEDBACK_TYPE_FEEDBACK,
    FEEDBACK_TYPE_COMPLAINT,
    FEEDBACK_TYPE_APPRECIATION,
    FEEDBACK_TYPE_REQUEST,
)

FEEDBACK_STATUS_OPEN = "open"
FEEDBACK_STATUS_IN_REVIEW = "in_review"
FEEDBACK_STATUS_RESPONDED = "responded"
FEEDBACK_STATUS_CLOSED = "closed"

FEEDBACK_STATUSES = (
    FEEDBACK_STATUS_OPEN,
    FEEDBACK_STATUS_IN_REVIEW,
    FEEDBACK_STATUS_RESPONDED,
    FEEDBACK_STATUS_CLOSED,
)
